### PR TITLE
Add code to handle AMR label sequence.

### PR DESCRIPTION
**Pull request by tsimafeip**
Here is my contribution to enable AM-parser training for AMR label sequence. There are parallel repos, that need to be used as well to run the whole pipeline: am-tools and non-graph-formalisms-parsing.

### CODE REVIEW

**Comment by jgroschwitz** [comment]
Thanks for the pull request! This looks all good to me, except that I think the folder trained_amr_label_seq_model_full should not be included. The files in it are relatively large, and they all look like system output to me, so they could be recreated if needed. Can you make a new pull request without that folder (I cannot exclude it from my end)?

**Comment by tsimafeip** [comment]
Hello, Jonas! Thank you for the comment, I just forgot to add my local commit to the final PR. I have updated it and squashed commits.

**Comment by tsimafeip** [comment]
Also, we need to merge the PR to am-tools - https://github.com/coli-saar/am-tools/pull/11/commits/2f471a32066f32eb0e34bbaae7ccd1567ab6d8dd.

**Comment by jgroschwitz** [comment]
All done! Thanks again!

**Pull request merged**
