### PR TITLE
Setup Docker environment.

### PR DESCRIPTION
**Pull request by tsimafeip**
Hello! Here is a PR, which helps to setup Docker environment to am-parser.

### CODE REVIEW

**Comment by alexanderkoller** [comment]
This is cool. One question: Does this Docker environment support GPU acceleration? I remember that you had to use special Docker images from Nvidia if you wanted GPU.

**Comment by tsimafeip** [comment]
Yes, Docker supports GPU acceleration. You can need to set '--gpus' option for 'run' command. I have updated README to reflect it.

**Comment by megodoonch** [comment]
This is really helpful! I'm using this fork now, but I don't feel qualified to approve the merge. 
I am getting an error on train, but I have no idea if it has anything to do with this pull request. The line that's causing problems is also in the main branch.

**Comment by jgroschwitz** [comment]
I have manually added @megodoonch 's edit to specify the pytorch version  (https://github.com/tsimafeip/am-parser/pull/1)  in commit https://github.com/coli-saar/am-parser/commit/47c719d1df436c00c6eaf310d31c93340e9a9b99. (I did not include the formatting changes to unrelated files that were in that pull request)

**Pull request merged**
